apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: pipeline
    name: pipeline
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      type: None
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: " node() {\n
  stage ('build'){\n
  openshiftBuild(namespace: 'development', buildConfig: 'myphp', showBuildlog: 'true')}\n
stage ('Approve Deploy to development'){\n
timeout(time: 2, unit: 'DAYS') {input message: 'Approve to development?'}}\n\n
stage ('Deploy to development'){ \nopenshiftDeploy(namespace: 'development',deploymentConfig: 'myphp',replicaCount:'1')}\n
stage ('Approve Deploy to testing'){\n
timeout(time: 2, unit: 'DAYS') {input message: 'Approve to testing?'}}\n\n
stage ('Deploy to testing'){ \nopenshiftDeploy(namespace: 'testing',deploymentConfig: 'myphp',replicaCount:'1')}\n
stage ('Approve Deploy to production'){\n
timeout(time: 2, unit: 'DAYS') {input message: 'Approve to production?'}}\n\n
stage ('Deploy to production'){ \nopenshiftDeploy(namespace: 'production',deploymentConfig: 'myphp',replicaCount:'1')}\n
}"
type: JenkinsPipeline
triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
status:
    lastVersion: 0
