apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: pipeline
    name: pipeline
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      type: None
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: "node() {\n    stage 'build'\n    openshiftBuild(namespace: 'development',buildConfig:
          'myphp',showBuildLogs: 'true')\n    \n    stage 'deploy in Development'\n
          \   openshiftDeploy(namespace: 'development',deploymentConfig: 'myphp',replicaCount:'1')\n
          \   \n    stage 'Approve Deploy to Testing'\n    timeout(time: 2, unit:
          'DAYS') {\n        input message: 'Approve to Testing?'\n    }\n    \n    stage
          'deploy in Testing'\n    openshiftDeploy(namespace: 'testing',deploymentConfig:
          'myphp',replicaCount:'1')\n    \n    stage 'Approve Deploy to Production'\n
          \   timeout(time: 2, unit: 'DAYS') {\n        input message: 'Approve to
          Production?'\n    }\n    \n    stage 'deploy in Production'\n    openshiftDeploy(namespace:
          'production',deploymentConfig: 'myphp',replicaCount:'1')\n}"
      type: JenkinsPipeline
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
  status:
    lastVersion: 0
