apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: pipeline
    name: pipeline
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      type: None
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: " node() {\n
  stage ('build'){\n
    openshiftBuild(namespace: 'dev',buildConfig:'myphp',showBuildLogs: 'true')\n
  }\n
	stage ('Approve Deploy to dev'){\n 
	 timeout(time: 2, unit: 'DAYS') {input message: 'Approve to dev?'}\n
  }

	stage ('Deploy to dev'){ \n
	 openshiftDeploy(namespace: 'dev',deploymentConfig: 'myphp',replicaCount:'1')\n
  }\n

	stage ('Approve Deploy to test'){\n 
	 timeout(time: 2, unit: 'DAYS') {input message: 'Approve to test?'}\n
  }

	stage ('Deploy to test'){ \n
	 openshiftDeploy(namespace: 'test',deploymentConfig: 'myphp',replicaCount:'1')\n
  }\n

	stage ('Approve Deploy to prod'){\n 
	 timeout(time: 2, unit: 'DAYS') {input message: 'Approve to prod?'}\n
  }

	stage ('Deploy to prod'){ \n
	 openshiftDeploy(namespace: 'prod',deploymentConfig: 'myphp',replicaCount:'1')\n
  }\n

}"
type: JenkinsPipeline
triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
status:
    lastVersion: 0